### ISSUE TITLE
[FIXED] reward doesn't check for full inventory

### ISSUE THREAD

**Issue by pliesveld** [ZwerOxotnik/m-lawful-evil#10]
![image](https://user-images.githubusercontent.com/2522505/82138542-4e02b680-97ef-11ea-8c5a-d4d42ca920c3.png)

![image](https://user-images.githubusercontent.com/2522505/82138603-a6d24f00-97ef-11ea-8a77-5396355c9198.png)

note:  

[0.17.79] player.can_insert maybe bugged: 

https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.can_insert

full inventory:

![image](https://user-images.githubusercontent.com/2522505/82158754-be452280-9857-11ea-94f8-82e63320a8ee.png)

player.can_insert returns true

![image](https://user-images.githubusercontent.com/2522505/82158773-e46ac280-9857-11ea-969e-96298501eb6b.png)

**Comment by ZwerOxotnik** [comment]
@pliesveld, the issue probably still exists. I'll check it this/next week.

**Comment by ZwerOxotnik** [comment]
Hm, probably, order of effects matters in this case.

**Comment by ZwerOxotnik** [comment]
Maybe, https://github.com/ZwerOxotnik/m-lawful-evil/issues/12 should be fixed first.

**Comment by ZwerOxotnik** [comment]
It seems like there are no errors now.
