### ISSUE TITLE
[FIXED] Item stack count has to be a positive number

### ISSUE THREAD

**Issue by pliesveld** [ZwerOxotnik/m-lawful-evil#12]
version: 0.3.26

When a law is passed that involve the % fine, it is possible that the value returned is invalid:

https://github.com/ZwerOxotnik/m-lawful-evil/blob/937e09c43b186f63a53350212942cfba9c25e063/control.lua#L911

When invalid value is applied during EFFECT_TYPE_REWARD, player_insert fails with message 'Item stack count has to be a positive number:

https://github.com/ZwerOxotnik/m-lawful-evil/blob/937e09c43b186f63a53350212942cfba9c25e063/control.lua#L932

![image](https://user-images.githubusercontent.com/2522505/82138390-15aea880-97ee-11ea-9b33-80850ec36868.png)

**Comment by ZwerOxotnik** [comment]
@pliesveld, the issue probably still exists. I'll check it this/next week.

**Comment by ZwerOxotnik** [comment]
Fixed, uploaded https://mods.factorio.com/mod/m-lawful-evil/downloads
